# Generated by Django 4.1 on 2022-09-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have_watched', models.TextField()),
                ('movie_title', models.TextField()),
                ('movie_rating', models.IntegerField()),
                ('movie_release', models.IntegerField()),
                ('movie_review', models.TextField()),
            ],
        ),
    ]
