# Generated by Django 4.1 on 2022-09-22 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_rename_mywatchlist_mywatchlistitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyWatchListItem',
            new_name='MyWatchList',
        ),
    ]
